services:
  voicevox_engine:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  # rust:
  #   build: .
  #   working_dir: /app
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - PORT=9000
  #     - VOICEVOX_ENDPOINT=http://voicevox_engine:50020
