# prod
# @worker_origin = https://botcast-worker.w4k4.me
# dev
@worker_origin = http://localhost:9000

###
GET {{worker_origin}}/version

###
POST {{worker_origin}}/evalScript
Content-Type: application/json

{
  "$let": {
      "year": { "$eval": "today('%Y')" },
      "url": "https://www.aozora.gr.jp/cards/000081/files/45630_23908.html"
  },
  "in": {
    "title": "テスト",
    "sections": [
      {
        "type": "Serif",
        "speaker": "urn:voicevox:zunda:normal",
        "text": "今年は${year}年です。"
      },
      {
        "type": "Serif",
        "speaker": "a",
        "text": { "$eval": "text(fetch(url))" }
      }
    ]
  }
}
