[package]
name = "script_http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.128"
xmldecl = "0.2.0"
encoding = "0.2.33"
