[package]
name = "script_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
json-e = { git = "https://github.com/wakame-tech/json-e", branch = "fix-pub-context" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
