[package]
name = "audio_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
reqwest = { version = "0.12.7", features = ["json"] }
log = "0.4.22"
urlencoding = "2.1.3"
async-trait = "0.1.83"
